{"text": "\u201cThe world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\u201d", "author": "Albert Einstein", "tags": ["change", "deep-thoughts", "thinking", "world"], "links": ["http://quotes.toscrape.com/tag/change/page/1/", "http://quotes.toscrape.com/tag/deep-thoughts/page/1/", "http://quotes.toscrape.com/tag/thinking/page/1/", "http://quotes.toscrape.com/tag/world/page/1/"]}
{"text": "\u201cIt is our choices, Harry, that show what we truly are, far more than our abilities.\u201d", "author": "J.K. Rowling", "tags": ["abilities", "choices"], "links": ["http://quotes.toscrape.com/tag/abilities/page/1/", "http://quotes.toscrape.com/tag/choices/page/1/"]}
{"text": "\u201cThere are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.\u201d", "author": "Albert Einstein", "tags": ["inspirational", "life", "live", "miracle", "miracles"], "links": ["http://quotes.toscrape.com/tag/inspirational/page/1/", "http://quotes.toscrape.com/tag/life/page/1/", "http://quotes.toscrape.com/tag/live/page/1/", "http://quotes.toscrape.com/tag/miracle/page/1/", "http://quotes.toscrape.com/tag/miracles/page/1/"]}
{"text": "\u201cThe person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.\u201d", "author": "Jane Austen", "tags": ["aliteracy", "books", "classic", "humor"], "links": ["http://quotes.toscrape.com/tag/aliteracy/page/1/", "http://quotes.toscrape.com/tag/books/page/1/", "http://quotes.toscrape.com/tag/classic/page/1/", "http://quotes.toscrape.com/tag/humor/page/1/"]}
{"text": "\u201cImperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\u201d", "author": "Marilyn Monroe", "tags": ["be-yourself", "inspirational"], "links": ["http://quotes.toscrape.com/tag/be-yourself/page/1/", "http://quotes.toscrape.com/tag/inspirational/page/1/"]}
{"text": "\u201cTry not to become a man of success. Rather become a man of value.\u201d", "author": "Albert Einstein", "tags": ["adulthood", "success", "value"], "links": ["http://quotes.toscrape.com/tag/adulthood/page/1/", "http://quotes.toscrape.com/tag/success/page/1/", "http://quotes.toscrape.com/tag/value/page/1/"]}
{"text": "\u201cIt is better to be hated for what you are than to be loved for what you are not.\u201d", "author": "Andr\u00e9 Gide", "tags": ["life", "love"], "links": ["http://quotes.toscrape.com/tag/life/page/1/", "http://quotes.toscrape.com/tag/love/page/1/"]}
{"text": "\u201cI have not failed. I've just found 10,000 ways that won't work.\u201d", "author": "Thomas A. Edison", "tags": ["edison", "failure", "inspirational", "paraphrased"], "links": ["http://quotes.toscrape.com/tag/edison/page/1/", "http://quotes.toscrape.com/tag/failure/page/1/", "http://quotes.toscrape.com/tag/inspirational/page/1/", "http://quotes.toscrape.com/tag/paraphrased/page/1/"]}
{"text": "\u201cA woman is like a tea bag; you never know how strong it is until it's in hot water.\u201d", "author": "Eleanor Roosevelt", "tags": ["misattributed-eleanor-roosevelt"], "links": ["http://quotes.toscrape.com/tag/misattributed-eleanor-roosevelt/page/1/"]}
{"text": "\u201cA day without sunshine is like, you know, night.\u201d", "author": "Steve Martin", "tags": ["humor", "obvious", "simile"], "links": ["http://quotes.toscrape.com/tag/humor/page/1/", "http://quotes.toscrape.com/tag/obvious/page/1/", "http://quotes.toscrape.com/tag/simile/page/1/"]}
{"text": "\u201cThis life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.\u201d", "author": "Marilyn Monroe", "tags": ["friends", "heartbreak", "inspirational", "life", "love", "sisters"], "links": ["http://quotes.toscrape.com/tag/friends/page/1/", "http://quotes.toscrape.com/tag/heartbreak/page/1/", "http://quotes.toscrape.com/tag/inspirational/page/1/", "http://quotes.toscrape.com/tag/life/page/1/", "http://quotes.toscrape.com/tag/love/page/1/", "http://quotes.toscrape.com/tag/sisters/page/1/"]}
{"text": "\u201cIt takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.\u201d", "author": "J.K. Rowling", "tags": ["courage", "friends"], "links": ["http://quotes.toscrape.com/tag/courage/page/1/", "http://quotes.toscrape.com/tag/friends/page/1/"]}
{"text": "\u201cIf you can't explain it to a six year old, you don't understand it yourself.\u201d", "author": "Albert Einstein", "tags": ["simplicity", "understand"], "links": ["http://quotes.toscrape.com/tag/simplicity/page/1/", "http://quotes.toscrape.com/tag/understand/page/1/"]}
{"text": "\u201cYou may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect\u2014you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break\u2014her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.\u201d", "author": "Bob Marley", "tags": ["love"], "links": ["http://quotes.toscrape.com/tag/love/page/1/"]}
{"text": "\u201cI like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.\u201d", "author": "Dr. Seuss", "tags": ["fantasy"], "links": ["http://quotes.toscrape.com/tag/fantasy/page/1/"]}
{"text": "\u201cI may not have gone where I intended to go, but I think I have ended up where I needed to be.\u201d", "author": "Douglas Adams", "tags": ["life", "navigation"], "links": ["http://quotes.toscrape.com/tag/life/page/1/", "http://quotes.toscrape.com/tag/navigation/page/1/"]}
{"text": "\u201cThe opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.\u201d", "author": "Elie Wiesel", "tags": ["activism", "apathy", "hate", "indifference", "inspirational", "love", "opposite", "philosophy"], "links": ["http://quotes.toscrape.com/tag/activism/page/1/", "http://quotes.toscrape.com/tag/apathy/page/1/", "http://quotes.toscrape.com/tag/hate/page/1/", "http://quotes.toscrape.com/tag/indifference/page/1/", "http://quotes.toscrape.com/tag/inspirational/page/1/", "http://quotes.toscrape.com/tag/love/page/1/", "http://quotes.toscrape.com/tag/opposite/page/1/", "http://quotes.toscrape.com/tag/philosophy/page/1/"]}
{"text": "\u201cIt is not a lack of love, but a lack of friendship that makes unhappy marriages.\u201d", "author": "Friedrich Nietzsche", "tags": ["friendship", "lack-of-friendship", "lack-of-love", "love", "marriage", "unhappy-marriage"], "links": ["http://quotes.toscrape.com/tag/friendship/page/1/", "http://quotes.toscrape.com/tag/lack-of-friendship/page/1/", "http://quotes.toscrape.com/tag/lack-of-love/page/1/", "http://quotes.toscrape.com/tag/love/page/1/", "http://quotes.toscrape.com/tag/marriage/page/1/", "http://quotes.toscrape.com/tag/unhappy-marriage/page/1/"]}
{"text": "\u201cGood friends, good books, and a sleepy conscience: this is the ideal life.\u201d", "author": "Mark Twain", "tags": ["books", "contentment", "friends", "friendship", "life"], "links": ["http://quotes.toscrape.com/tag/books/page/1/", "http://quotes.toscrape.com/tag/contentment/page/1/", "http://quotes.toscrape.com/tag/friends/page/1/", "http://quotes.toscrape.com/tag/friendship/page/1/", "http://quotes.toscrape.com/tag/life/page/1/"]}
{"text": "\u201cLife is what happens to us while we are making other plans.\u201d", "author": "Allen Saunders", "tags": ["fate", "life", "misattributed-john-lennon", "planning", "plans"], "links": ["http://quotes.toscrape.com/tag/fate/page/1/", "http://quotes.toscrape.com/tag/life/page/1/", "http://quotes.toscrape.com/tag/misattributed-john-lennon/page/1/", "http://quotes.toscrape.com/tag/planning/page/1/", "http://quotes.toscrape.com/tag/plans/page/1/"]}
